In [3]:
model = load_model('data/lenet5_relu_model.h5')
conv2d_1_layer = model.get_layer("conv2d_1")
max_pooling2d_1_layer = model.get_layer("max_pooling2d_1")
conv2d_2_layer = model.get_layer("conv2d_2")
max_pooling2d_2_layer = model.get_layer("max_pooling2d_2")
dense_1_layer = model.get_layer("dense_1")
dense_2_layer = model.get_layer("dense_2")
dense_3_layer = model.get_layer("dense_3")
layers = {}
layers["conv2d_1"] = conv2d_1_layer
layers["max_pooling2d_1"] = max_pooling2d_1_layer
layers["conv2d_2"] = conv2d_2_layer
layers["max_pooling2d_2"] = max_pooling2d_2_layer
layers["dense_1_layer"] = dense_1_layer
layers["dense_2_layer"] = dense_2_layer
layers["dense_3_layer"] = dense_3_layer

In [6]:
mats['conv2d_1']

array([[[[ 0.06141106,  0.        , 10.797474  ,  0.        ,
           0.        , 13.840789  ],
         [ 0.        ,  0.        , 11.04663   ,  0.        ,
           0.        , 14.70165   ],
         [ 0.        ,  0.        , 11.295787  ,  0.        ,
           0.        , 15.5625105 ],
         ...,
         [ 0.        , 11.394578  , 17.77384   ,  0.        ,
           0.        , 37.94491   ],
         [ 0.        , 12.193295  , 18.023     ,  0.        ,
           0.        , 38.805763  ],
         [ 0.        , 12.992002  , 18.272158  ,  0.        ,
           0.        , 39.666626  ]],

        [[ 0.06141106,  0.        , 10.797474  ,  0.        ,
           0.        , 13.840789  ],
         [ 0.        ,  0.        , 11.04663   ,  0.        ,
           0.        , 14.70165   ],
         [ 0.        ,  0.        , 11.295787  ,  0.        ,
           0.        , 15.5625105 ],
         ...,
         [ 0.        , 11.394578  , 17.77384   ,  0.        ,
           0.    

In [12]:
arr = np.arange(15).reshape((3, 5))
for i in arr:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
arr = np.arange(15).reshape((3, 5))
arr2 = arr + 1
print(arr2)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
(arr2 * arr).sum()

1120

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])