In [24]:
import numpy as np
import h5py 

In [28]:
arr = np.arange(2*3*4).reshape((2, 3, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
stack0 = np.stack(arr, axis=0)
print(stack0.shape)
print(stack0)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [38]:
print(arr[1, :, :])
print(arr[0, :, :])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
stack1 = np.stack(arr, axis=1)
print(stack1.shape)
print(stack1)

(3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [39]:
print(arr[:, 0, :])
print(arr[:, 1, :])
print(arr[:, 2, :])

[[ 0  1  2  3]
 [12 13 14 15]]
[[ 4  5  6  7]
 [16 17 18 19]]
[[ 8  9 10 11]
 [20 21 22 23]]


In [41]:
stack2 = np.stack(arr, axis=-1)
print(stack2.shape)
print(stack2)

(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [42]:
print(arr[:, :, 0])
print(arr[:, :, 1])
print(arr[:, :, 2])
print(arr[:, :, 3])

[[ 0  4  8]
 [12 16 20]]
[[ 1  5  9]
 [13 17 21]]
[[ 2  6 10]
 [14 18 22]]
[[ 3  7 11]
 [15 19 23]]
